/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Movie } from "./Movie";
export * as factories from "./factories";
export { Movie__factory } from "./factories/Movie__factory";
